name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow the workflow to be triggered manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Generate Doxygen documentation
        uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: docs/Doxyfile
          folder: html
